const states = {
  emptyApp: {
    config: {
      openLeftPanel: true,
      mode: 'edit',
      openBottomPanel: true,
      openRightPanel: true,
      openDebugger: false,
      scale: 100,
      selectedComponents: [],
      selectedAction: null,
      cachedAction: null,
      showDot: false,
      expandedKeys: [],
      canvasHeight: 280,
      canvasWidth: 1172,
      isOnline: true,
      hoveredComponents: [],
      expandedWidgets: {},
      wsStatus: {
        DASHBOARD: 'INIT',
        APP: 'CONNECTED',
        APP_BINARY: 'CONNECTED',
        AI_AGENT: 'INIT',
      },
      draggingComponentIDs: [],
      resizingComponentIDs: [],
    },
    currentApp: {
      components: {
        root: {
          version: 0,
          displayName: 'root',
          parentNode: '',
          showName: 'root',
          childrenNode: ['page1'],
          type: 'DOT_PANEL',
          containerType: 'EDITOR_DOT_PANEL',
          h: 0,
          w: 0,
          minH: 0,
          minW: 0,
          x: -1,
          y: -1,
          z: 0,
          props: {
            currentPageIndex: 0,
            pageSortedKey: ['page1'],
          },
        },
        page1: {
          version: 0,
          displayName: 'page1',
          parentNode: 'root',
          showName: 'page',
          childrenNode: ['bodySection1', 'modalSection1'],
          type: 'PAGE_NODE',
          containerType: 'EDITOR_PAGE_SQUARE',
          h: 0,
          w: 0,
          minH: 0,
          minW: 0,
          x: -1,
          y: -1,
          z: 0,
          props: {
            bodyColumns: 32,
            bottomHeight: 0,
            canvasSize: 'auto',
            canvasWidth: 100,
            footerColumns: 32,
            hasFooter: false,
            hasHeader: false,
            hasLeft: false,
            hasRight: false,
            headerColumns: 32,
            isFooterFixed: true,
            isHeaderFixed: true,
            isLeftFixed: true,
            isRightFixed: true,
            layout: 'default',
            leftColumns: 8,
            leftPosition: 'NONE',
            leftWidth: 0,
            rightColumns: 8,
            rightPosition: 'NONE',
            rightWidth: 0,
            showLeftFoldIcon: false,
            showRightFoldIcon: false,
            topHeight: 0,
          },
        },
        bodySection1: {
          version: 0,
          displayName: 'bodySection1',
          parentNode: 'page1',
          showName: 'bodySection',
          childrenNode: ['bodySection1-bodySectionContainer1'],
          type: 'SECTION_NODE',
          containerType: 'EDITOR_LAYOUT_SQUARE',
          h: 0,
          w: 0,
          minH: 0,
          minW: 0,
          x: -1,
          y: -1,
          z: 0,
          props: {
            currentViewIndex: 0,
            defaultViewKey: 'sub-page1',
            sectionViewConfigs: [
              {
                id: 'a8199cd5-e146-4668-a377-a2b2c3e361c8',
                key: 'sub-page1',
                path: 'sub-page1',
                viewDisplayName: 'bodySection1-bodySectionContainer1',
              },
            ],
            style: {
              padding: {
                mode: 'all',
                size: '24',
              },
            },
            viewSortedKey: ['bodySection1-bodySectionContainer1'],
          },
        },
        'bodySection1-bodySectionContainer1': {
          version: 0,
          displayName: 'bodySection1-bodySectionContainer1',
          parentNode: 'bodySection1',
          showName: 'bodySection1-bodySectionContainer1',
          childrenNode: [],
          type: 'CONTAINER_NODE',
          containerType: 'EDITOR_DOT_PANEL',
          h: 0,
          w: 0,
          minH: 0,
          minW: 0,
          x: -1,
          y: -1,
          z: 0,
          props: {},
        },
        modalSection1: {
          version: 0,
          displayName: 'modalSection1',
          parentNode: 'page1',
          showName: 'modalSection',
          childrenNode: [],
          type: 'MODAL_SECTION_NODE',
          containerType: 'EDITOR_LAYOUT_SQUARE',
          h: 0,
          w: 0,
          minH: 0,
          minW: 0,
          x: -1,
          y: -1,
          z: 0,
          props: {},
        },
      },
      action: [],
      appInfo: {
        appId: 'ILAfx4p1C7dY',
        uid: 'cde1270b-85ae-4912-a232-5f5cb3337203',
        teamID: 'ILAfx4p1C7d0',
        appName: 'app1',
        releaseVersion: 0,
        mainlineVersion: 0,
        deployed: false,
        config: {
          public: false,
          waterMark: true,
          description: '',
          publishedToMarketplace: false,
          publishWithAIAgent: false,
          cover: '',
          appType: 'pc',
          components: [],
          actions: [],
        },
        updatedBy: 'ILAfx4p1C7dZ',
        updatedAt: '2024-10-20T13:30:53.568788Z',
        appActivity: {
          modifier: 'root',
          modifiedAt: '2024-10-20T13:30:53.568788Z',
        },
        editedBy: [
          {
            userID: 'ILAfx4p1C7dZ',
            nickname: 'root',
            email: 'root',
            avatar: '',
            editedAt: '2024-10-20T13:30:53.568788469Z',
          },
        ],
      },
      collaborators: {
        inRoomUsers: [
          {
            id: 'ILAfx4p1C7dZ',
            nickname: 'root',
            avatar: '',
          },
        ],
        components: {},
      },
      execution: {
        dependencies: {
          'currentPageInfo.pagePath': ['root.pageSortedKey', 'root.currentPageIndex'],
          'currentPageInfo.subPagePath': ['root.currentSubPagePath'],
        },
        result: {
          root: {
            currentPageIndex: 0,
            pageSortedKey: ['page1'],
            displayName: 'root',
            $parentNode: '',
            $type: 'WIDGET',
            $widgetType: 'DOT_PANEL',
            $childrenNode: ['page1'],
          },
          page1: {
            bodyColumns: 32,
            bottomHeight: 0,
            canvasSize: 'auto',
            canvasWidth: 100,
            footerColumns: 32,
            hasFooter: false,
            hasHeader: false,
            hasLeft: false,
            hasRight: false,
            headerColumns: 32,
            isFooterFixed: true,
            isHeaderFixed: true,
            isLeftFixed: true,
            isRightFixed: true,
            layout: 'default',
            leftColumns: 8,
            leftPosition: 'NONE',
            leftWidth: 0,
            rightColumns: 8,
            rightPosition: 'NONE',
            rightWidth: 0,
            showLeftFoldIcon: false,
            showRightFoldIcon: false,
            topHeight: 0,
            displayName: 'page1',
            $parentNode: 'root',
            $type: 'WIDGET',
            $widgetType: 'PAGE_NODE',
            $childrenNode: ['bodySection1', 'modalSection1'],
            $parentPageName: 'page1',
          },
          bodySection1: {
            currentViewIndex: 0,
            defaultViewKey: 'sub-page1',
            sectionViewConfigs: [
              {
                id: 'a8199cd5-e146-4668-a377-a2b2c3e361c8',
                key: 'sub-page1',
                path: 'sub-page1',
                viewDisplayName: 'bodySection1-bodySectionContainer1',
              },
            ],
            style: {
              padding: {
                mode: 'all',
                size: '24',
              },
            },
            viewSortedKey: ['bodySection1-bodySectionContainer1'],
            displayName: 'bodySection1',
            $parentNode: 'page1',
            $type: 'WIDGET',
            $widgetType: 'SECTION_NODE',
            $childrenNode: ['bodySection1-bodySectionContainer1'],
            $parentPageName: 'page1',
          },
          modalSection1: {
            displayName: 'modalSection1',
            $parentNode: 'page1',
            $type: 'WIDGET',
            $widgetType: 'MODAL_SECTION_NODE',
            $childrenNode: [],
            $parentPageName: 'page1',
          },
          builderInfo: {
            version: '4.8.3',
            language: 'English',
          },
          currentUserInfo: {
            userID: 'ILAfx4p1C7dZ',
            nickname: 'root',
            email: 'root',
            language: 'en-US',
            createdAt: '2024-10-17T04:43:25.519489Z',
            updatedAt: '2024-10-17T04:44:07.468633Z',
          },
          globalData: {
            $dynamicAttrPaths: [],
          },
          urlParams: {
            query: {},
            url: 'http://localhost:3000/0/app/ILAfx4p1C7dY',
            appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dY',
          },
          localStorage: {},
          currentPageInfo: {
            pagePath: 'page1',
            $dynamicAttrPaths: ['pagePath', 'subPagePath'],
          },
          pageInfos: [
            {
              pagePath: '/page1',
              subPagePath: '/page1/sub-page1',
              pageName: 'page1',
              subPageName: 'sub-page1',
              isHomePage: true,
              subPageGroup: '',
            },
          ],
        },
        error: {},
        independencies: {
          'root.currentSubPagePath': ['currentPageInfo.subPagePath'],
          'root.pageSortedKey': ['currentPageInfo.pagePath'],
          'root.currentPageIndex': ['currentPageInfo.pagePath'],
        },
      },
      cursor: {},
      dragShadow: {},
      layoutInfo: {
        widgetsLayoutInfo: {
          root: {
            displayName: 'root',
            parentNode: '',
            widgetType: 'DOT_PANEL',
            childrenNode: ['page1'],
            containerType: 'EDITOR_DOT_PANEL',
            layoutInfo: {
              x: -1,
              y: -1,
              z: 0,
              w: 0,
              h: 0,
              minW: 1,
              minH: 0,
            },
          },
          page1: {
            displayName: 'page1',
            parentNode: 'root',
            widgetType: 'PAGE_NODE',
            childrenNode: ['bodySection1', 'modalSection1'],
            containerType: 'EDITOR_PAGE_SQUARE',
            layoutInfo: {
              x: -1,
              y: -1,
              z: 0,
              w: 0,
              h: 0,
              minW: 1,
              minH: 0,
            },
          },
          bodySection1: {
            displayName: 'bodySection1',
            parentNode: 'page1',
            widgetType: 'SECTION_NODE',
            childrenNode: ['bodySection1-bodySectionContainer1'],
            containerType: 'EDITOR_LAYOUT_SQUARE',
            layoutInfo: {
              x: -1,
              y: -1,
              z: 0,
              w: 0,
              h: 0,
              minW: 1,
              minH: 0,
            },
          },
          'bodySection1-bodySectionContainer1': {
            displayName: 'bodySection1-bodySectionContainer1',
            parentNode: 'bodySection1',
            widgetType: 'CONTAINER_NODE',
            childrenNode: [],
            containerType: 'EDITOR_DOT_PANEL',
            layoutInfo: {
              x: -1,
              y: -1,
              z: 0,
              w: 0,
              h: 0,
              minW: 1,
              minH: 0,
            },
          },
          modalSection1: {
            displayName: 'modalSection1',
            parentNode: 'page1',
            widgetType: 'MODAL_SECTION_NODE',
            childrenNode: [],
            containerType: 'EDITOR_LAYOUT_SQUARE',
            layoutInfo: {
              x: -1,
              y: -1,
              z: 0,
              w: 0,
              h: 0,
              minW: 1,
              minH: 0,
            },
          },
        },
      },
    },
    currentAppHistory: {
      snapshotList: [],
      totalPages: 0,
      currentPage: 0,
      hasMore: false,
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    resource: [],
    guide: {
      currentStep: 0,
      isOpen: false,
    },
    currentUser: {
      userID: 'ILAfx4p1C7dZ',
      uid: '158504d6-a47d-43a0-879e-79a57981cecc',
      nickname: 'root',
      email: 'root',
      avatar: '',
      language: 'en-US',
      isTutorialViewed: true,
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    team: {
      currentId: 'ILAfx4p1C7d0',
      items: [
        {
          id: 'ILAfx4p1C7d0',
          uid: '83cfb484-0a3f-4bfd-aab3-70432d021cab',
          name: 'my-team',
          identifier: '0',
          icon: 'https://cdn.illacloud.com/email-template/people.png',
          myRole: 1,
          teamMemberID: 'ILAfx4p1C7dZ',
          teamMemberPermission: {
            config: 0,
          },
          permission: {
            allowEditorInvite: true,
            allowViewerInvite: true,
            allowEditorManageTeamMember: true,
            allowViewerManageTeamMember: true,
            inviteLinkEnabled: true,
            blockRegister: false,
          },
        },
      ],
    },
    aiAgent: {
      list: [],
    },
  },

  componentPanel: {
    Props: {
      sessionType: 'COMMON',
      sessionTitle: 'Commonly components',
      widgetCardInfos: [
        {
          id: 'INPUTS-INPUT_WIDGET-input',
          keywords: ['Input', '文本输入框'],
          widgetType: 'INPUT_WIDGET',
          widgetName: 'Input',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'input',
          isPremiumWidget: false,
        },
        {
          id: 'INPUTS-NUMBER_INPUT_WIDGET-numberInput',
          keywords: ['Number Input', '数字输入框'],
          widgetType: 'NUMBER_INPUT_WIDGET',
          widgetName: 'Number Input',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'numberInput',
          isPremiumWidget: false,
        },
        {
          id: 'DATA-DATA_GRID_WIDGET-dataGrid',
          keywords: ['dataGrid', '数据表格', 'table', '表格'],
          widgetType: 'DATA_GRID_WIDGET',
          widgetName: 'Data grid',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'dataGrid',
          isPremiumWidget: false,
        },
        {
          id: 'DATA-CHART_WIDGET-chart',
          keywords: ['Chart', '图表'],
          widgetType: 'CHART_WIDGET',
          widgetName: 'Chart',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'chart',
          isPremiumWidget: false,
        },
        {
          id: 'CONTAINER-CONTAINER_WIDGET-container',
          keywords: ['container', '容器'],
          widgetType: 'CONTAINER_WIDGET',
          widgetName: 'Container',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'container',
          isPremiumWidget: false,
        },
        {
          id: 'CONTAINER-FORM_WIDGET-form',
          keywords: ['form', '表单'],
          widgetType: 'FORM_WIDGET',
          widgetName: 'Form',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'form',
          isPremiumWidget: false,
        },
        {
          id: 'CONTAINER-MODAL_WIDGET-modal',
          keywords: ['modal', '对话框'],
          widgetType: 'MODAL_WIDGET',
          widgetName: 'Modal',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'modal',
          isPremiumWidget: false,
        },
        {
          id: 'PRESENTATION-TEXT_WIDGET-text',
          keywords: ['Text', '文本'],
          widgetType: 'TEXT_WIDGET',
          widgetName: 'Text',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'text',
          isPremiumWidget: false,
        },
        {
          id: 'PRESENTATION-IMAGE_WIDGET-image',
          keywords: ['Image', '图片'],
          widgetType: 'IMAGE_WIDGET',
          widgetName: 'Image',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'image',
          isPremiumWidget: false,
        },
        {
          id: 'PRESENTATION-BUTTON_WIDGET-button',
          keywords: ['Button', '按钮'],
          widgetType: 'BUTTON_WIDGET',
          widgetName: 'Button',
          icon: {
            key: null,
            ref: null,
            props: {},
            _owner: null,
            _store: {},
          },
          displayName: 'button',
          isPremiumWidget: false,
        },
      ],
    },
    Hooks: [
      {
        id: null,
        isStateEditable: false,
        name: 'Selector2',
        value: false,
        subHooks: [
          {
            id: null,
            isStateEditable: false,
            name: 'ReduxContext2',
            subHooks: [
              {
                id: null,
                isStateEditable: false,
                name: 'ReactRedux',
                value: {
                  store: {
                    liftedStore: {},
                  },
                  subscription: {},
                  stabilityCheck: 'once',
                  identityFunctionCheck: 'once',
                },
                subHooks: [],
                debugInfo: null,
                hookSource: {
                  lineNumber: 146,
                  functionName: 'useReduxContext2',
                  fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
                  columnNumber: 32,
                },
              },
            ],
            debugInfo: null,
            hookSource: {
              lineNumber: 184,
              columnNumber: 9,
              functionName: 'useSelector2',
              fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
            },
          },
          {
            id: 0,
            isStateEditable: false,
            name: 'Ref',
            value: false,
            subHooks: [],
            debugInfo: null,
            hookSource: {
              lineNumber: 185,
              functionName: 'useSelector2',
              fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
              columnNumber: 28,
            },
          },
          {
            id: 1,
            isStateEditable: false,
            name: 'Callback',
            subHooks: [],
            debugInfo: null,
            hookSource: {
              lineNumber: 186,
              functionName: 'useSelector2',
              fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
              columnNumber: 35,
            },
          },
          {
            id: null,
            isStateEditable: false,
            name: 'SyncExternalStoreWithSelector3',
            value: false,
            subHooks: [
              {
                id: 2,
                isStateEditable: false,
                name: 'Ref',
                value: {
                  hasValue: true,
                  value: false,
                },
                subHooks: [],
                debugInfo: null,
                hookSource: {
                  lineNumber: 27,
                  functionName: 'useSyncExternalStoreWithSelector3',
                  fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
                  columnNumber: 25,
                },
              },
              {
                id: 3,
                isStateEditable: false,
                name: 'Memo',
                value: [null, null],
                subHooks: [],
                debugInfo: null,
                hookSource: {
                  lineNumber: 38,
                  functionName: 'useSyncExternalStoreWithSelector3',
                  fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
                  columnNumber: 26,
                },
              },
              {
                id: 4,
                isStateEditable: false,
                name: 'SyncExternalStore',
                value: false,
                subHooks: [],
                debugInfo: null,
                hookSource: {
                  lineNumber: 81,
                  functionName: 'useSyncExternalStoreWithSelector3',
                  fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
                  columnNumber: 23,
                },
              },
              {
                id: 5,
                isStateEditable: false,
                name: 'Effect',
                subHooks: [],
                debugInfo: null,
                hookSource: {
                  lineNumber: 82,
                  functionName: 'useSyncExternalStoreWithSelector3',
                  fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
                  columnNumber: 11,
                },
              },
            ],
            debugInfo: null,
            hookSource: {
              lineNumber: 243,
              columnNumber: 27,
              functionName: 'useSelector2',
              fileName: 'http://localhost:3000/node_modules/.vite/deps/chunk-F6ZLQ7P7.js?v=150e8946',
            },
          },
        ],
        debugInfo: null,
        hookSource: {
          lineNumber: 19,
          columnNumber: 25,
          fileName: 'http://localhost:3000/src/page/App/components/ComponentPanel/ComponentSession.tsx',
        },
      },
    ],
  },

  Provider: {
    config: {
      openLeftPanel: true,
      mode: 'edit',
      openBottomPanel: true,
      openRightPanel: true,
      openDebugger: false,
      scale: 100,
      selectedComponents: [],
      selectedAction: null,
      cachedAction: null,
      showDot: false,
      expandedKeys: [],
      canvasHeight: 1080,
      canvasWidth: 1920,
      isOnline: true,
      hoveredComponents: [],
      expandedWidgets: {},
      wsStatus: {
        DASHBOARD: 'INIT',
        APP: 'INIT',
        APP_BINARY: 'INIT',
        AI_AGENT: 'INIT',
      },
      draggingComponentIDs: [],
      resizingComponentIDs: [],
    },
    currentApp: {
      openLeftPanel: true,
      mode: 'edit',
      openBottomPanel: true,
      openRightPanel: true,
      openDebugger: false,
      scale: 100,
      selectedComponents: [],
      selectedAction: null,
      cachedAction: null,
      showDot: false,
      expandedKeys: [],
      canvasHeight: 1080,
      canvasWidth: 1920,
      isOnline: true,
      hoveredComponents: [],
      expandedWidgets: {},
      wsStatus: {
        DASHBOARD: 'INIT',
        APP: 'INIT',
        APP_BINARY: 'INIT',
        AI_AGENT: 'INIT',
      },
      draggingComponentIDs: [],
      resizingComponentIDs: [],
    },
    currentAppHistory: {
      snapshotList: [],
      totalPages: 0,
      currentPage: 0,
      hasMore: false,
    },
    builderInfo: {
      snapshotList: [],
      totalPages: 0,
      currentPage: 0,
      hasMore: false,
    },
    resource: [],
    guide: {
      currentStep: 0,
      isOpen: false,
    },
    currentUser: {
      userID: '',
      uid: '',
      nickname: '',
      language: '',
      email: '',
      avatar: '',
      isTutorialViewed: false,
      isPasswordSet: false,
      ssoVerified: {
        github: false,
        google: false,
      },
      isNewUser: false,
      haveAppSumoSubscription: false,
      doesAppSumoSubscriptionAppliedToTeam: false,
      createdAt: '',
      updatedAt: '',
    },
    team: {},
    aiAgent: {
      list: [],
    },
  },

  Provider_App: {
    typography: {
      copiedToolTip: 'Copied',
      copyToolTip: 'Copy',
      expandLabel: 'Expand',
    },
    timePicker: {
      ok: 'OK',
      placeholder: 'Select time',
      placeholders: ['Start time', 'End time'],
      now: 'Now',
    },
    popover: {
      close: 'Close',
    },
    empty: {
      noData: 'No data',
    },
    pagination: {
      total: 'Total {0}',
      page: 'Page',
      go: 'Go to ',
    },
    upload: {
      start: 'Start',
      cancel: 'Cancel',
      upload: 'Upload',
      delete: 'Delete',
      preview: 'Preview',
      retry: 'Click to retry',
      dragTip: 'Drag and drop the file',
      selectFile: 'Select File',
      beginUpload: 'Upload File',
      error: 'Failed',
    },
    popConfirm: {
      confirm: 'Confirm',
      cancel: 'Cancel',
    },
    calendar: {
      year: 'Year',
      month: 'Month',
      day: 'Day',
      today: 'today',
      week: 'Week',
      Monday: 'Mon',
      Tuesday: 'Tue',
      Wednesday: 'Wed',
      Thursday: 'Thu',
      Friday: 'Fri',
      Saturday: 'Sat',
      Sunday: 'Sun',
      January: 'Jan',
      February: 'Feb',
      March: 'Mar',
      April: 'Apr',
      May: 'May',
      June: 'Jun',
      July: 'Jul',
      August: 'Aug',
      September: 'Sep',
      October: 'Oct',
      November: 'Nov',
      December: 'Dec',
      startDate: 'StartDate',
      endDate: 'EndDate',
    },
    datePicker: {
      year: 'Year',
      month: 'Month',
      day: 'Day',
      today: 'Today',
      week: 'Week',
      Monday: 'Mon',
      Tuesday: 'Tue',
      Wednesday: 'Wed',
      Thursday: 'Thu',
      Friday: 'Fri',
      Saturday: 'Sat',
      Sunday: 'Sun',
      January: 'January',
      February: 'February',
      March: 'March',
      April: 'April',
      May: 'May',
      June: 'June',
      July: 'July',
      August: 'August',
      September: 'September',
      October: 'October',
      November: 'November',
      December: 'December',
      okText: 'OK',
      nowText: 'Now',
      timeText: 'Time',
    },
    modal: {
      okText: 'OK',
      cancelText: 'Cancel',
    },
    drawer: {
      okText: 'OK',
      cancelText: 'Cancel',
    },
  },

  RouterProvider: {
    State: {
      historyAction: 'POP',
      location: {
        pathname: '/0/app/ILAfx4p1C7dY',
        search: '',
        hash: '',
        state: null,
        key: 'default',
      },
      matches: [
        {
          params: {
            teamIdentifier: '0',
            appId: 'ILAfx4p1C7dY',
          },
          pathname: '/0/app/ILAfx4p1C7dY',
          pathnameBase: '/0/app/ILAfx4p1C7dY',
          route: {
            path: '/:teamIdentifier/app/:appId',
            errorElement: {
              key: null,
              ref: null,
              props: {
                children: {
                  type: {
                    _payload: {
                      _status: -1,
                    },
                  },
                  key: null,
                  ref: null,
                  props: {},
                  _owner: null,
                  _store: {},
                },
              },
              _owner: null,
              _store: {},
            },
            element: {
              key: null,
              ref: null,
              props: {
                desktopPage: {
                  key: null,
                  ref: null,
                  props: {
                    children: {
                      type: {
                        _payload: {
                          _status: 1,
                          _result: {},
                        },
                      },
                      key: null,
                      ref: null,
                      props: {},
                      _owner: null,
                      _store: {},
                    },
                  },
                  _owner: null,
                  _store: {},
                },
              },
              _owner: null,
              _store: {},
            },
            hasErrorBoundary: true,
            id: '2',
          },
        },
      ],
      initialized: true,
      navigation: {
        state: 'idle',
      },
      restoreScrollPosition: null,
      preventScrollReset: false,
      revalidation: 'idle',
      loaderData: {
        '2': null,
      },
      actionData: null,
      errors: null,
      fetchers: {},
      blockers: {},
    },
  },

  Editor: {
    DebugValue: {
      userID: 'ILAfx4p1C7dZ',
      uid: '158504d6-a47d-43a0-879e-79a57981cecc',
      nickname: 'root',
      email: 'root',
      avatar: '',
      language: 'en-US',
      isTutorialViewed: true,
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
  },
};
