const dataLayer = [
    {
        "gtm.start": 1695022719170,
        "event": "gtm.js",
        "gtm.uniqueEventId": 1
    },
    {
        "0": "js",
        "1": "2023-09-18T07:38:39.171Z"
    },
    {
        "0": "config",
        "1": "AW-617640813"
    },
    {
        "0": "js",
        "1": "2023-09-18T07:38:39.171Z"
    },
    {
        "0": "config",
        "1": "867030291"
    },
    {
        "0": "send",
        "1": "pageview",
        "2": {
            "send_page_view": false
        }
    },
    {
        "0": "get",
        "1": "G-CMNNJGSJVV",
        "2": "session_id"
    },
    {
        "0": "get",
        "1": "G-CMNNJGSJVV",
        "2": "session_number"
    },
    {
        "0": "get",
        "1": "G-CMNNJGSJVV",
        "2": "client_id"
    },
    {
        "0": [
            "cuUserLocation",
            "{\"ip\":\"203.194.43.61\",\"type\":\"ipv4\",\"continent_code\":\"OC\",\"continent_name\":\"Oceania\",\"country_code\":\"AU\",\"country_name\":\"Australia\",\"region_code\":\"NSW\",\"region_name\":\"New South Wales\",\"city\":\"Parramatta\",\"zip\":\"2138\",\"latitude\":-33.84199905395508,\"longitude\":151.08399963378906,\"location\":{\"geoname_id\":7281840,\"capital\":\"Canberra\",\"languages\":[{\"code\":\"en\",\"name\":\"English\",\"native\":\"English\"}],\"country_flag\":\"https://assets.ipstack.com/flags/au.svg\",\"country_flag_emoji\":\"🇦🇺\",\"country_flag_emoji_unicode\":\"U+1F1E6 U+1F1FA\",\"calling_code\":\"61\",\"is_eu\":false},\"time_zone\":{\"id\":\"Australia/Sydney\",\"current_time\":\"2023-09-16T18:13:53+10:00\",\"gmt_offset\":36000,\"code\":\"AEST\",\"is_daylight_saving\":false},\"currency\":{\"code\":\"AUD\",\"name\":\"Australian Dollar\",\"plural\":\"Australian dollars\",\"symbol\":\"AU$\",\"symbol_native\":\"$\"},\"connection\":{\"asn\":7545,\"isp\":\"Tpg Telecom Limited\"}}"
        ]
    },
    {
        "event": "gtm.dom",
        "gtm.uniqueEventId": 6
    },
    {
        "gtm.start": 1695022720056,
        "event": "gtm.js",
        "gtm.uniqueEventId": 10
    },
    {
        "event": "gtm.load",
        "gtm.uniqueEventId": 11
    },
    {
        "view type": "list",
        "parentType": "Subcategory",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "views a view",
        "gtm.uniqueEventId": 12
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 13
    },
    {
        "via": "view",
        "view": "list",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "edit custom field value",
        "gtm.uniqueEventId": 14
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 15
    },
    {
        "via": "home",
        "viaCardName": "lineup",
        "taskVersion": "V2",
        "isSubtask": "false",
        "layout": "",
        "view": "",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open task",
        "gtm.uniqueEventId": 16
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 17
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 18
    },
    {
        "isOpen": false,
        "availableSeatCount": 0,
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "update empty seats people page banner state",
        "gtm.uniqueEventId": 19
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 20
    },
    {
        "app": null,
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open legacy app",
        "gtm.uniqueEventId": 21
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 22
    },
    {
        "paywall name": "private views",
        "paywall trigger": "",
        "paywall type": "pop-up",
        "team size": 1,
        "version": "old",
        "email": "peterjaberau@gmail.com",
        "uses entitlements": false,
        "paywall limit treatment": "excluded",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "trigger paywall",
        "gtm.uniqueEventId": 23
    },
    {
        "paywall name": "custom task ids",
        "paywall trigger": "restricted feature - business",
        "paywall type": "pop-up",
        "team size": 1,
        "version": "old",
        "email": "peterjaberau@gmail.com",
        "uses entitlements": false,
        "paywall limit treatment": "excluded",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "trigger paywall",
        "gtm.uniqueEventId": 24
    },
    {
        "nested subtasks": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 25
    },
    {
        "not started status group": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 26
    },
    {
        "preview word, excel, and powerpoint files": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 27
    },
    {
        "time estimates rollup": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 28
    },
    {
        "time tracking rollup": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 29
    },
    {
        "paywall name": "time in status clickapp",
        "paywall trigger": "restricted feature - business",
        "paywall type": "pop-up",
        "team size": 1,
        "version": "old",
        "email": "peterjaberau@gmail.com",
        "uses entitlements": false,
        "paywall limit treatment": "excluded",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "trigger paywall",
        "gtm.uniqueEventId": 30
    },
    {
        "paywall name": "private universal search",
        "paywall trigger": "usage",
        "paywall type": "pop-up",
        "team size": 1,
        "email": "peterjaberau@gmail.com",
        "uses entitlements": true,
        "plan recommended": "Business Plus",
        "cta type": "checkout",
        "limits": "",
        "version": "configurable",
        "paywall limit treatment": "excluded",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "trigger paywall",
        "gtm.uniqueEventId": 31
    },
    {
        "zoom": true,
        "via": "clickapps page",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "enable clickapp",
        "gtm.uniqueEventId": 32
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 33
    },
    {
        "bannerName": "ai banner pricing page",
        "bannerType": "top navigation",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "view banner",
        "gtm.uniqueEventId": 34
    },
    {
        "pageVariation": "original design",
        "unlimitedPrice": 7,
        "businessPrice": 12,
        "businessPlusPrice": 19,
        "currencySymbol": "$",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open pricing page",
        "gtm.uniqueEventId": 35
    },
    {
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "plan comparison table scrolled into view",
        "gtm.uniqueEventId": 36
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 37
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 38
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 39
    },
    {
        "app": null,
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open legacy app",
        "gtm.uniqueEventId": 40
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 41
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 42
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 43
    },
    {
        "isOpen": false,
        "availableSeatCount": 0,
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "update empty seats people page banner state",
        "gtm.uniqueEventId": 44
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 45
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 46
    },
    {
        "view type": "board",
        "parentType": "Category",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "views a view",
        "gtm.uniqueEventId": 47
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 48
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 49
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 50
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 51
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 52
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 53
    },
    {
        "via": "user settings menu",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open app center",
        "gtm.uniqueEventId": 54
    },
    {
        "page": "apps",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "navigate app center",
        "gtm.uniqueEventId": 55
    },
    {
        "page": "apps",
        "category": "featured",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "navigate app center",
        "gtm.uniqueEventId": 56
    },
    {
        "page": "apps",
        "category": "calendars",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "navigate app center",
        "gtm.uniqueEventId": 57
    },
    {
        "page": "apps",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "navigate app center",
        "gtm.uniqueEventId": 58
    },
    {
        "page": "static app",
        "app": "googlecalendar",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "navigate app center",
        "gtm.uniqueEventId": 59
    },
    {
        "via": "user settings",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "open template center",
        "gtm.uniqueEventId": 60
    },
    {
        "paywall name": "dashboards",
        "paywall trigger": "usage",
        "paywall type": "page",
        "team size": 1,
        "email": "peterjaberau@gmail.com",
        "version": "old",
        "uses entitlements": false,
        "paywall limit treatment": "excluded",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "trigger paywall",
        "gtm.uniqueEventId": 61
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 62
    },
    {
        "event": "page_view_settled",
        "isFirstPageSettledEvent": false,
        "gtm.uniqueEventId": 63
    },
    {
        "via": "search button",
        "enabledFeatureFlags": [],
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "view search",
        "gtm.uniqueEventId": 64
    },
    {
        "objectClicked": "calendar",
        "via": "home",
        "username": "peterjaberau@gmail.com",
        "userRoleId": 1,
        "userRole": "Owner",
        "workspaceDomain": "gmail.com",
        "workspaceName": "Peter Jaber's Workspace",
        "workspaceID": "36698333",
        "screenWidth": 2009,
        "screenHeight": 862,
        "planName": "Free Forever",
        "planCode": "1",
        "planTier": "FreeForever",
        "plan_info_id": "1",
        "plan_info_name": "freeforever",
        "plan_id": "1",
        "trialPlanName": null,
        "appVersion": "2.197.1",
        "desktopAppVersion": null,
        "platform": "Web",
        "cuAnnoID": "46",
        "isMobile": false,
        "sessionId": "1695022711",
        "clientId": "476750639.1684026422",
        "sessionNumber": 53,
        "cuLanguage": "en-US",
        "cuV3Eligible": false,
        "cuVersion": "2.0",
        "cuVersionTaskView": "2.0",
        "cuVersionInbox": "2.0",
        "userId": "48763417",
        "segmentAnonymousId": "abc4f3a5-2de4-4ae5-b664-4f6f9ec72d40",
        "event": "click home top navigation options",
        "gtm.uniqueEventId": 65
    }
]

const highlightJS = {
    "versionString": "11.0.1",
    "MATCH_NOTHING_RE": {},
    "IDENT_RE": "[a-zA-Z]\\w*",
    "UNDERSCORE_IDENT_RE": "[a-zA-Z_]\\w*",
    "NUMBER_RE": "\\b\\d+(\\.\\d+)?",
    "C_NUMBER_RE": "(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)",
    "BINARY_NUMBER_RE": "\\b(0b[01]+)",
    "RE_STARTERS_RE": "!|!=|!==|%|%=|&|&&|&=|\\*|\\*=|\\+|\\+=|,|-|-=|/=|/|:|;|<<|<<=|<=|<|===|==|=|>>>=|>>=|>=|>>>|>>|>|\\?|\\[|\\{|\\(|\\^|\\^=|\\||\\|=|\\|\\||~",
    "BACKSLASH_ESCAPE": {
        "begin": "\\\\[\\s\\S]",
        "relevance": 0
    },
    "APOS_STRING_MODE": {
        "scope": "string",
        "begin": "'",
        "end": "'",
        "illegal": "\\n",
        "contains": [
            {
                "begin": "\\\\[\\s\\S]",
                "relevance": 0
            }
        ]
    },
    "QUOTE_STRING_MODE": {
        "scope": "string",
        "begin": "\"",
        "end": "\"",
        "illegal": "\\n",
        "contains": [
            {
                "begin": "\\\\[\\s\\S]",
                "relevance": 0
            }
        ]
    },
    "PHRASAL_WORDS_MODE": {
        "begin": {}
    },
    "C_LINE_COMMENT_MODE": {
        "scope": "comment",
        "begin": "//",
        "end": "$",
        "contains": [
            {
                "scope": "doctag",
                "begin": "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)",
                "end": {},
                "excludeBegin": true,
                "relevance": 0
            },
            {
                "begin": "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}"
            }
        ]
    },
    "C_BLOCK_COMMENT_MODE": {
        "scope": "comment",
        "begin": "/\\*",
        "end": "\\*/",
        "contains": [
            {
                "scope": "doctag",
                "begin": "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)",
                "end": {},
                "excludeBegin": true,
                "relevance": 0
            },
            {
                "begin": "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}"
            }
        ]
    },
    "HASH_COMMENT_MODE": {
        "scope": "comment",
        "begin": "#",
        "end": "$",
        "contains": [
            {
                "scope": "doctag",
                "begin": "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)",
                "end": {},
                "excludeBegin": true,
                "relevance": 0
            },
            {
                "begin": "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}"
            }
        ]
    },
    "NUMBER_MODE": {
        "scope": "number",
        "begin": "\\b\\d+(\\.\\d+)?",
        "relevance": 0
    },
    "C_NUMBER_MODE": {
        "scope": "number",
        "begin": "(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)",
        "relevance": 0
    },
    "BINARY_NUMBER_MODE": {
        "scope": "number",
        "begin": "\\b(0b[01]+)",
        "relevance": 0
    },
    "REGEXP_MODE": {
        "begin": {},
        "contains": [
            {
                "scope": "regexp",
                "begin": {},
                "end": {},
                "illegal": {},
                "contains": [
                    {
                        "begin": "\\\\[\\s\\S]",
                        "relevance": 0
                    },
                    {
                        "begin": {},
                        "end": {},
                        "relevance": 0,
                        "contains": [
                            {
                                "begin": "\\\\[\\s\\S]",
                                "relevance": 0
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "TITLE_MODE": {
        "scope": "title",
        "begin": "[a-zA-Z]\\w*",
        "relevance": 0
    },
    "UNDERSCORE_TITLE_MODE": {
        "scope": "title",
        "begin": "[a-zA-Z_]\\w*",
        "relevance": 0
    },
    "METHOD_GUARD": {
        "begin": "\\.\\s*[a-zA-Z_]\\w*",
        "relevance": 0
    }
}
