const CodeEditor = {
  getExecutionResultToCurrentPageCodeMirror: {
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
      $dynamicAttrPaths: ['pagePath', 'subPagePath'],
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
    input1: {
      value: '{{}}',
      defaultValue: '{{}}',
      label: 'Label',
      labelAlign: 'left',
      labelPosition: 'left',
      labelWidth: 33,
      colorScheme: 'blue',
      hidden: false,
      formDataKey: 'input1',
      placeholder: 'input sth',
      $dynamicAttrPaths: ['labelWidth', 'formDataKey', 'showVisibleButton', 'defaultValue'],
      type: 'input',
      showVisibleButton: true,
      displayName: 'input1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'INPUT_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        type: 'String',
        defaultValue: 'String',
        placeholder: 'String',
        label: 'String',
        labelCaption: 'String',
        labelWidth: 'Number',
        disabled: 'Boolean',
        readOnly: 'Boolean',
        showVisibleButton: 'Boolean',
        allowClear: 'Boolean',
        showCharacterCount: 'Boolean',
        prefixText: 'String',
        suffixText: 'String',
        tooltipText: 'String',
        required: 'Boolean',
        regex: 'String',
        maxLength: 'Number',
        minLength: 'Number',
        customRule: 'String',
        hideValidationMessage: 'Boolean',
        formDataKey: 'String',
        hidden: 'Boolean',
      },
    },
  },

  getExecutionResultToGlobalCodeMirror: {
    button1: {
      $dynamicAttrPaths: ['text'],
      colorScheme: 'blue',
      hidden: false,
      text: 'root',
      variant: 'fill',
      displayName: 'button1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'BUTTON_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        text: 'String',
        loading: 'Boolean',
        disabled: 'Boolean',
        tooltipText: 'String',
        hidden: 'Boolean',
      },
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    globalData: {
      state1: '',
      $dynamicAttrPaths: [],
    },
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dY',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dY',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
      $dynamicAttrPaths: ['pagePath', 'subPagePath'],
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
  },

  props: {
    props: {
      scopeOfAutoComplete: 'page',
      value: '{{input1.displayName}}',
      showLineNumbers: false,
      expectValueType: 'String',
      lang: 'javascript',
      maxHeight: '208px',
      maxWidth: '100%',
      codeType: 'EXPRESSION',
      modalTitle: 'Form Data Key',
      modalDescription: 'Specify a key of a wrapping form component when constructing the data attribute.',
    },
    tmpCalcContext: {
      builderInfo: {
        version: '4.8.3',
        language: 'English',
      },
      currentUserInfo: {
        userID: 'ILAfx4p1C7dZ',
        nickname: 'root',
        email: 'root',
        language: 'en-US',
        createdAt: '2024-10-17T04:43:25.519489Z',
        updatedAt: '2024-10-17T04:44:07.468633Z',
      },
      urlParams: {
        query: {},
        url: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
        appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
      },
      localStorage: {},
      currentPageInfo: {
        pagePath: 'page1',
        $dynamicAttrPaths: ['pagePath', 'subPagePath'],
      },
      pageInfos: [
        {
          pagePath: '/page1',
          subPagePath: '/page1/sub-page1',
          pageName: 'page1',
          subPageName: 'sub-page1',
          isHomePage: true,
          subPageGroup: '',
        },
      ],
      input1: {
        value: '',
        defaultValue: '',
        label: 'Label',
        labelAlign: 'left',
        labelPosition: 'left',
        labelWidth: 33,
        colorScheme: 'blue',
        hidden: false,
        formDataKey: 'input1',
        placeholder: 'input sth',
        $dynamicAttrPaths: ['labelWidth', 'formDataKey', 'showVisibleButton'],
        type: 'input',
        showVisibleButton: true,
        displayName: 'input1',
        $parentNode: 'bodySection1-bodySectionContainer1',
        $type: 'WIDGET',
        $widgetType: 'INPUT_WIDGET',
        $childrenNode: [],
        $parentPageName: 'page1',
        $validationPaths: {
          type: 'String',
          defaultValue: 'String',
          placeholder: 'String',
          label: 'String',
          labelCaption: 'String',
          labelWidth: 'Number',
          disabled: 'Boolean',
          readOnly: 'Boolean',
          showVisibleButton: 'Boolean',
          allowClear: 'Boolean',
          showCharacterCount: 'Boolean',
          prefixText: 'String',
          suffixText: 'String',
          tooltipText: 'String',
          required: 'Boolean',
          regex: 'String',
          maxLength: 'Number',
          minLength: 'Number',
          customRule: 'String',
          hideValidationMessage: 'Boolean',
          formDataKey: 'String',
          hidden: 'Boolean',
        },
      },
    },
    calcContext: {
      builderInfo: {
        version: '4.8.3',
        language: 'English',
      },
      currentUserInfo: {
        userID: 'ILAfx4p1C7dZ',
        nickname: 'root',
        email: 'root',
        language: 'en-US',
        createdAt: '2024-10-17T04:43:25.519489Z',
        updatedAt: '2024-10-17T04:44:07.468633Z',
      },
      urlParams: {
        query: {},
        url: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
        appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
      },
      localStorage: {},
      currentPageInfo: {
        pagePath: 'page1',
      },
      pageInfos: [
        {
          pagePath: '/page1',
          subPagePath: '/page1/sub-page1',
          pageName: 'page1',
          subPageName: 'sub-page1',
          isHomePage: true,
          subPageGroup: '',
        },
      ],
      input1: {
        value: '',
        defaultValue: '',
        label: 'Label',
        labelAlign: 'left',
        labelPosition: 'left',
        labelWidth: 33,
        colorScheme: 'blue',
        hidden: false,
        formDataKey: 'input1',
        placeholder: 'input sth',
        type: 'input',
        showVisibleButton: true,
        displayName: 'input1',
      },
    },
    stringSnippets: [
      {
        value: '{{input1.displayName}}',
        hasError: false,
      },
    ],
  },

  props_autoComplete: {
    props: {
      scopeOfAutoComplete: 'page',
      value: '{{input1.displayName}}',
      showLineNumbers: false,
      expectValueType: 'String',
      lang: 'javascript',
      maxHeight: '208px',
      maxWidth: '100%',
      codeType: 'EXPRESSION',
      modalTitle: 'Form Data Key',
      modalDescription: 'Specify a key of a wrapping form component when constructing the data attribute.',
    },
    tmpCalcContext: {
      builderInfo: {
        version: '4.8.3',
        language: 'English',
      },
      currentUserInfo: {
        userID: 'ILAfx4p1C7dZ',
        nickname: 'root',
        email: 'root',
        language: 'en-US',
        createdAt: '2024-10-17T04:43:25.519489Z',
        updatedAt: '2024-10-17T04:44:07.468633Z',
      },
      urlParams: {
        query: {},
        url: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
        appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
      },
      localStorage: {},
      currentPageInfo: {
        pagePath: 'page1',
        $dynamicAttrPaths: ['pagePath', 'subPagePath'],
      },
      pageInfos: [
        {
          pagePath: '/page1',
          subPagePath: '/page1/sub-page1',
          pageName: 'page1',
          subPageName: 'sub-page1',
          isHomePage: true,
          subPageGroup: '',
        },
      ],
      input1: {
        value: '{{}}',
        defaultValue: '{{}}',
        label: 'Label',
        labelAlign: 'left',
        labelPosition: 'left',
        labelWidth: 33,
        colorScheme: 'blue',
        hidden: false,
        formDataKey: 'input1',
        placeholder: 'input sth',
        $dynamicAttrPaths: ['labelWidth', 'formDataKey', 'showVisibleButton', 'defaultValue'],
        type: 'input',
        showVisibleButton: true,
        displayName: 'input1',
        $parentNode: 'bodySection1-bodySectionContainer1',
        $type: 'WIDGET',
        $widgetType: 'INPUT_WIDGET',
        $childrenNode: [],
        $parentPageName: 'page1',
        $validationPaths: {
          type: 'String',
          defaultValue: 'String',
          placeholder: 'String',
          label: 'String',
          labelCaption: 'String',
          labelWidth: 'Number',
          disabled: 'Boolean',
          readOnly: 'Boolean',
          showVisibleButton: 'Boolean',
          allowClear: 'Boolean',
          showCharacterCount: 'Boolean',
          prefixText: 'String',
          suffixText: 'String',
          tooltipText: 'String',
          required: 'Boolean',
          regex: 'String',
          maxLength: 'Number',
          minLength: 'Number',
          customRule: 'String',
          hideValidationMessage: 'Boolean',
          formDataKey: 'String',
          hidden: 'Boolean',
        },
      },
    },
    calcContext: {
      builderInfo: {
        version: '4.8.3',
        language: 'English',
      },
      currentUserInfo: {
        userID: 'ILAfx4p1C7dZ',
        nickname: 'root',
        email: 'root',
        language: 'en-US',
        createdAt: '2024-10-17T04:43:25.519489Z',
        updatedAt: '2024-10-17T04:44:07.468633Z',
      },
      urlParams: {
        query: {},
        url: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
        appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dV',
      },
      localStorage: {},
      currentPageInfo: {
        pagePath: 'page1',
      },
      pageInfos: [
        {
          pagePath: '/page1',
          subPagePath: '/page1/sub-page1',
          pageName: 'page1',
          subPageName: 'sub-page1',
          isHomePage: true,
          subPageGroup: '',
        },
      ],
      input1: {
        value: '{{}}',
        defaultValue: '{{}}',
        label: 'Label',
        labelAlign: 'left',
        labelPosition: 'left',
        labelWidth: 33,
        colorScheme: 'blue',
        hidden: false,
        formDataKey: 'input1',
        placeholder: 'input sth',
        type: 'input',
        showVisibleButton: true,
        displayName: 'input1',
      },
    },
    stringSnippets: [
      {
        value: '{{input1.displayName}}',
        hasError: false,
      },
    ],
  },
};

const CodeEditor1 = {
  props: {
    value: '// Tip: assign your external references to variables instead of chaining off the curly brackets.\nreturn 5',
    showLineNumbers: true,
    canShowCompleteInfo: true,
    height: '88px',
    expectValueType: 'String',
    lang: 'javascript',
    codeType: 'NO_METHOD_FUNCTION',
  },
  tmpCalcContext: {
    transformer1: {
      $actionID: 'ILAfx4p1C7dZ',
      $resourceID: 'ILAfx4p1C7d0',
      displayName: 'transformer1',
      actionType: 'transformer',
      $type: 'ACTION',
      $dynamicAttrPaths: ['value'],
      value: 5,
      $context: {
        '(function (){// Tip: assign your external references to variables instead of chaining off the curly brackets.\nreturn 5})()': 5,
      },
    },
    dataGrid1: {
      $dynamicAttrPaths: ['dataSourceJS'],
      columns: [
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'id',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'id',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'name',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'name',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'email',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'email',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'type',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'type',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'age',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'age',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'paid',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'paid',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: '$uniqueID',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: '$uniqueID',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
      ],
      dataSource: [],
      dataSourceJS: [
        {
          id: 1,
          name: 'Elvera Sleite',
          email: 'hboshers50@narod.ru',
          type: 'product manager',
          age: 30,
          paid: true,
        },
        {
          id: 2,
          name: 'Richardo Durrett',
          email: 'mhamsleyt@ask.com',
          type: 'UX/UI',
          age: 18,
          paid: false,
        },
        {
          id: 3,
          name: 'Ellwood Halsted',
          email: 'amccardle5h@godaddy.com',
          type: 'designer',
          age: 14,
          paid: true,
        },
        {
          id: 4,
          name: 'Tyson Anersen',
          email: 'hstrettell3c@list-manage.com',
          type: 'UX/UI',
          age: 32,
          paid: true,
        },
        {
          id: 5,
          name: 'Tobey Mordy',
          email: 'gfraschetti54@independent.co.uk',
          type: 'designer',
          age: 22,
          paid: true,
        },
        {
          id: 6,
          name: 'Leena Stovine',
          email: 'prawlingson4w@phoca.cz',
          type: 'designer',
          age: 17,
          paid: false,
        },
        {
          id: 7,
          name: 'Erinn Olenchenko',
          email: 'cmeddows1q@aboutads.info',
          type: 'UX/UI',
          age: 17,
          paid: false,
        },
        {
          id: 8,
          name: 'Jilly Aldiss',
          email: 'radamik2b@hubpages.com',
          type: 'marketing',
          age: 22,
          paid: false,
        },
        {
          id: 9,
          name: 'Erinn Reasce',
          email: 'aduckeru@scribd.com',
          type: 'designer',
          age: 24,
          paid: false,
        },
        {
          id: 10,
          name: 'Sargent Guy',
          email: 'jmaccafferky57@archive.org',
          type: 'marketing',
          age: 19,
          paid: false,
        },
        {
          id: 11,
          name: 'Gay Craiker',
          email: 'ddurrett42@yahoo.com',
          type: ['UX/UI', 'designer'],
          age: 27,
          paid: false,
        },
        {
          id: 12,
          name: 'Piper Sorey',
          email: 'dscanterburyx@topsy.com',
          type: 'designer',
          age: 25,
          paid: true,
        },
        {
          id: 13,
          name: 'Renato Benjefield',
          email: 'dmayfield27@seattletimes.com',
          type: 'marketing',
          age: 27,
          paid: true,
        },
        {
          id: 14,
          name: 'Adelind Loache',
          email: 'vhessel2w@sciencedirect.com',
          type: ['designer', 'UX/UI'],
          age: 14,
          paid: true,
        },
        {
          id: 15,
          name: 'Pepi Corssen',
          email: 'bfifield2v@amazonaws.com',
          type: ['product manager', 'designer'],
          age: 27,
          paid: false,
        },
      ],
      dataSourceMode: 'dynamic',
      enablePagination: false,
      excludeHiddenColumns: true,
      sortOrder: 'default',
      displayName: 'dataGrid1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'DATA_GRID_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        loading: 'Boolean',
        primaryKey: 'String',
        sortKey: 'String',
        rowSelection: 'Boolean',
        enablePagination: 'Boolean',
        enableServerSidePagination: 'Boolean',
        totalRowCount: 'Number',
        pageSize: 'Number',
        page: 'Number',
        pageSizeOptions: 'Array',
        densitySetting: 'Boolean',
        columnSetting: 'Boolean',
        refreshSetting: 'Boolean',
        exportSetting: 'Boolean',
        exportAllSetting: 'Boolean',
        filterSetting: 'Boolean',
        quickFilterSetting: 'Boolean',
        excludeHiddenColumns: 'Boolean',
      },
      pageSize: 5,
      page: 0,
      selectedRowsPrimaryKeys: [],
      selectedRows: [],
    },
    container1: {
      $dynamicAttrPaths: [],
      backgroundColor: '#ffffffff',
      currentIndex: 0,
      currentKey: 'View 1',
      dynamicHeight: 'auto',
      padding: {
        mode: 'all',
        size: '24',
      },
      radius: '4px',
      resizeDirection: 'HORIZONTAL',
      shadow: 'small',
      viewList: [
        {
          id: '391bfe4b-70d0-4c27-b75f-1b117031e923',
          key: 'View 1',
          label: 'View 1',
        },
        {
          id: '6c97c982-877a-46f7-ad30-94d8b7979c15',
          key: 'View 2',
          label: 'View 2',
        },
        {
          id: 'c77e6a30-652e-425d-90b8-f7a36145f8e4',
          key: 'View 3',
          label: 'View 3',
        },
      ],
      displayName: 'container1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'CONTAINER_WIDGET',
      $childrenNode: ['canvas1', 'canvas2', 'canvas3'],
      $parentPageName: 'page1',
      $validationPaths: {
        viewList: [
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
        ],
        tooltipText: 'String',
      },
    },
    button1: {
      $dynamicAttrPaths: [],
      colorScheme: 'blue',
      events: [
        {
          eventType: 'click',
          id: 'events-36330e2e-e37d-48e9-b77c-09ec25ea768d',
          method: 'trigger',
          targetId: 'query1',
          type: 'datasource',
        },
        {
          actionType: 'datasource',
          eventType: 'click',
          id: 'events-02f78d57-925c-4791-b1a9-890aae2d5d90',
        },
      ],
      hidden: false,
      text: 'Button',
      variant: 'fill',
      displayName: 'button1',
      $parentNode: 'canvas1',
      $type: 'WIDGET',
      $widgetType: 'BUTTON_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        text: 'String',
        events: [
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
        ],
        loading: 'Boolean',
        disabled: 'Boolean',
        tooltipText: 'String',
        hidden: 'Boolean',
      },
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    globalData: {
      $dynamicAttrPaths: [],
    },
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
      $dynamicAttrPaths: ['pagePath', 'subPagePath'],
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
  },
  calcContext: {
    transformer1: {
      displayName: 'transformer1',
      actionType: 'transformer',
      value: 5,
    },
    dataGrid1: {
      columns: [
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'id',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'id',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'name',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'name',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'email',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'email',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'type',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'type',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'age',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'age',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'paid',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'paid',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: '$uniqueID',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: '$uniqueID',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
      ],
      dataSource: [],
      dataSourceJS: [
        {
          id: 1,
          name: 'Elvera Sleite',
          email: 'hboshers50@narod.ru',
          type: 'product manager',
          age: 30,
          paid: true,
        },
        {
          id: 2,
          name: 'Richardo Durrett',
          email: 'mhamsleyt@ask.com',
          type: 'UX/UI',
          age: 18,
          paid: false,
        },
        {
          id: 3,
          name: 'Ellwood Halsted',
          email: 'amccardle5h@godaddy.com',
          type: 'designer',
          age: 14,
          paid: true,
        },
        {
          id: 4,
          name: 'Tyson Anersen',
          email: 'hstrettell3c@list-manage.com',
          type: 'UX/UI',
          age: 32,
          paid: true,
        },
        {
          id: 5,
          name: 'Tobey Mordy',
          email: 'gfraschetti54@independent.co.uk',
          type: 'designer',
          age: 22,
          paid: true,
        },
        {
          id: 6,
          name: 'Leena Stovine',
          email: 'prawlingson4w@phoca.cz',
          type: 'designer',
          age: 17,
          paid: false,
        },
        {
          id: 7,
          name: 'Erinn Olenchenko',
          email: 'cmeddows1q@aboutads.info',
          type: 'UX/UI',
          age: 17,
          paid: false,
        },
        {
          id: 8,
          name: 'Jilly Aldiss',
          email: 'radamik2b@hubpages.com',
          type: 'marketing',
          age: 22,
          paid: false,
        },
        {
          id: 9,
          name: 'Erinn Reasce',
          email: 'aduckeru@scribd.com',
          type: 'designer',
          age: 24,
          paid: false,
        },
        {
          id: 10,
          name: 'Sargent Guy',
          email: 'jmaccafferky57@archive.org',
          type: 'marketing',
          age: 19,
          paid: false,
        },
        {
          id: 11,
          name: 'Gay Craiker',
          email: 'ddurrett42@yahoo.com',
          type: ['UX/UI', 'designer'],
          age: 27,
          paid: false,
        },
        {
          id: 12,
          name: 'Piper Sorey',
          email: 'dscanterburyx@topsy.com',
          type: 'designer',
          age: 25,
          paid: true,
        },
        {
          id: 13,
          name: 'Renato Benjefield',
          email: 'dmayfield27@seattletimes.com',
          type: 'marketing',
          age: 27,
          paid: true,
        },
        {
          id: 14,
          name: 'Adelind Loache',
          email: 'vhessel2w@sciencedirect.com',
          type: ['designer', 'UX/UI'],
          age: 14,
          paid: true,
        },
        {
          id: 15,
          name: 'Pepi Corssen',
          email: 'bfifield2v@amazonaws.com',
          type: ['product manager', 'designer'],
          age: 27,
          paid: false,
        },
      ],
      dataSourceMode: 'dynamic',
      enablePagination: false,
      excludeHiddenColumns: true,
      sortOrder: 'default',
      displayName: 'dataGrid1',
      pageSize: 5,
      page: 0,
      selectedRowsPrimaryKeys: [],
      selectedRows: [],
    },
    container1: {
      backgroundColor: '#ffffffff',
      currentIndex: 0,
      currentKey: 'View 1',
      dynamicHeight: 'auto',
      padding: {
        mode: 'all',
        size: '24',
      },
      radius: '4px',
      resizeDirection: 'HORIZONTAL',
      shadow: 'small',
      viewList: [
        {
          id: '391bfe4b-70d0-4c27-b75f-1b117031e923',
          key: 'View 1',
          label: 'View 1',
        },
        {
          id: '6c97c982-877a-46f7-ad30-94d8b7979c15',
          key: 'View 2',
          label: 'View 2',
        },
        {
          id: 'c77e6a30-652e-425d-90b8-f7a36145f8e4',
          key: 'View 3',
          label: 'View 3',
        },
      ],
      displayName: 'container1',
    },
    button1: {
      colorScheme: 'blue',
      events: [
        {
          eventType: 'click',
          id: 'events-36330e2e-e37d-48e9-b77c-09ec25ea768d',
          method: 'trigger',
          targetId: 'query1',
          type: 'datasource',
        },
        {
          actionType: 'datasource',
          eventType: 'click',
          id: 'events-02f78d57-925c-4791-b1a9-890aae2d5d90',
        },
      ],
      hidden: false,
      text: 'Button',
      variant: 'fill',
      displayName: 'button1',
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    globalData: {},
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
  },
  stringSnippets: [],

  getExecutionResultToCurrentPageCodeMirror: {
    transformer1: {
      $actionID: 'ILAfx4p1C7dZ',
      $resourceID: 'ILAfx4p1C7d0',
      displayName: 'transformer1',
      actionType: 'transformer',
      $type: 'ACTION',
      $dynamicAttrPaths: ['value'],
      value: 5,
      $context: {
        '(function (){// Tip: assign your external references to variables instead of chaining off the curly brackets.\nreturn 5})()': 5,
      },
    },
    dataGrid1: {
      $dynamicAttrPaths: ['dataSourceJS'],
      columns: [
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'id',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'id',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'name',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'name',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'email',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'email',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'type',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'type',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'age',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'age',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'paid',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'paid',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: '$uniqueID',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: '$uniqueID',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
      ],
      dataSource: [],
      dataSourceJS: [
        {
          id: 1,
          name: 'Elvera Sleite',
          email: 'hboshers50@narod.ru',
          type: 'product manager',
          age: 30,
          paid: true,
        },
        {
          id: 2,
          name: 'Richardo Durrett',
          email: 'mhamsleyt@ask.com',
          type: 'UX/UI',
          age: 18,
          paid: false,
        },
        {
          id: 3,
          name: 'Ellwood Halsted',
          email: 'amccardle5h@godaddy.com',
          type: 'designer',
          age: 14,
          paid: true,
        },
        {
          id: 4,
          name: 'Tyson Anersen',
          email: 'hstrettell3c@list-manage.com',
          type: 'UX/UI',
          age: 32,
          paid: true,
        },
        {
          id: 5,
          name: 'Tobey Mordy',
          email: 'gfraschetti54@independent.co.uk',
          type: 'designer',
          age: 22,
          paid: true,
        },
        {
          id: 6,
          name: 'Leena Stovine',
          email: 'prawlingson4w@phoca.cz',
          type: 'designer',
          age: 17,
          paid: false,
        },
        {
          id: 7,
          name: 'Erinn Olenchenko',
          email: 'cmeddows1q@aboutads.info',
          type: 'UX/UI',
          age: 17,
          paid: false,
        },
        {
          id: 8,
          name: 'Jilly Aldiss',
          email: 'radamik2b@hubpages.com',
          type: 'marketing',
          age: 22,
          paid: false,
        },
        {
          id: 9,
          name: 'Erinn Reasce',
          email: 'aduckeru@scribd.com',
          type: 'designer',
          age: 24,
          paid: false,
        },
        {
          id: 10,
          name: 'Sargent Guy',
          email: 'jmaccafferky57@archive.org',
          type: 'marketing',
          age: 19,
          paid: false,
        },
        {
          id: 11,
          name: 'Gay Craiker',
          email: 'ddurrett42@yahoo.com',
          type: ['UX/UI', 'designer'],
          age: 27,
          paid: false,
        },
        {
          id: 12,
          name: 'Piper Sorey',
          email: 'dscanterburyx@topsy.com',
          type: 'designer',
          age: 25,
          paid: true,
        },
        {
          id: 13,
          name: 'Renato Benjefield',
          email: 'dmayfield27@seattletimes.com',
          type: 'marketing',
          age: 27,
          paid: true,
        },
        {
          id: 14,
          name: 'Adelind Loache',
          email: 'vhessel2w@sciencedirect.com',
          type: ['designer', 'UX/UI'],
          age: 14,
          paid: true,
        },
        {
          id: 15,
          name: 'Pepi Corssen',
          email: 'bfifield2v@amazonaws.com',
          type: ['product manager', 'designer'],
          age: 27,
          paid: false,
        },
      ],
      dataSourceMode: 'dynamic',
      enablePagination: false,
      excludeHiddenColumns: true,
      sortOrder: 'default',
      displayName: 'dataGrid1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'DATA_GRID_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        loading: 'Boolean',
        primaryKey: 'String',
        sortKey: 'String',
        rowSelection: 'Boolean',
        enablePagination: 'Boolean',
        enableServerSidePagination: 'Boolean',
        totalRowCount: 'Number',
        pageSize: 'Number',
        page: 'Number',
        pageSizeOptions: 'Array',
        densitySetting: 'Boolean',
        columnSetting: 'Boolean',
        refreshSetting: 'Boolean',
        exportSetting: 'Boolean',
        exportAllSetting: 'Boolean',
        filterSetting: 'Boolean',
        quickFilterSetting: 'Boolean',
        excludeHiddenColumns: 'Boolean',
      },
      pageSize: 5,
      page: 0,
      selectedRowsPrimaryKeys: [],
      selectedRows: [],
    },
    container1: {
      $dynamicAttrPaths: [],
      backgroundColor: '#ffffffff',
      currentIndex: 0,
      currentKey: 'View 1',
      dynamicHeight: 'auto',
      padding: {
        mode: 'all',
        size: '24',
      },
      radius: '4px',
      resizeDirection: 'HORIZONTAL',
      shadow: 'small',
      viewList: [
        {
          id: '391bfe4b-70d0-4c27-b75f-1b117031e923',
          key: 'View 1',
          label: 'View 1',
        },
        {
          id: '6c97c982-877a-46f7-ad30-94d8b7979c15',
          key: 'View 2',
          label: 'View 2',
        },
        {
          id: 'c77e6a30-652e-425d-90b8-f7a36145f8e4',
          key: 'View 3',
          label: 'View 3',
        },
      ],
      displayName: 'container1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'CONTAINER_WIDGET',
      $childrenNode: ['canvas1', 'canvas2', 'canvas3'],
      $parentPageName: 'page1',
      $validationPaths: {
        viewList: [
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
        ],
        tooltipText: 'String',
      },
    },
    button1: {
      $dynamicAttrPaths: ['text'],
      colorScheme: 'blue',
      events: [
        {
          eventType: 'click',
          id: 'events-36330e2e-e37d-48e9-b77c-09ec25ea768d',
          method: 'trigger',
          targetId: 'query1',
          type: 'datasource',
        },
        {
          actionType: 'datasource',
          eventType: 'click',
          id: 'events-02f78d57-925c-4791-b1a9-890aae2d5d90',
        },
      ],
      hidden: false,
      text: '{{}}',
      variant: 'fill',
      displayName: 'button1',
      $parentNode: 'canvas1',
      $type: 'WIDGET',
      $widgetType: 'BUTTON_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        text: 'String',
        events: [
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
        ],
        loading: 'Boolean',
        disabled: 'Boolean',
        tooltipText: 'String',
        hidden: 'Boolean',
      },
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
      $dynamicAttrPaths: ['pagePath', 'subPagePath'],
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
  },

  getExecutionResultToGlobalCodeMirror: {
    transformer1: {
      $actionID: 'ILAfx4p1C7dZ',
      $resourceID: 'ILAfx4p1C7d0',
      displayName: 'transformer1',
      actionType: 'transformer',
      $type: 'ACTION',
      $dynamicAttrPaths: ['value'],
      value: 5,
      $context: {
        '(function (){// Tip: assign your external references to variables instead of chaining off the curly brackets.\nreturn 5})()': 5,
      },
    },
    dataGrid1: {
      $dynamicAttrPaths: ['dataSourceJS'],
      columns: [
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'id',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'id',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'name',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'name',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'email',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'email',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'type',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'type',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'age',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'age',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: 'paid',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: 'paid',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
        {
          aggregable: true,
          columnType: 'auto',
          description: '',
          disableReorder: false,
          field: '$uniqueID',
          filterable: true,
          groupable: true,
          headerAlign: 'left',
          headerName: '$uniqueID',
          hideable: true,
          isCalc: true,
          pinnable: true,
          resizable: true,
          sortable: true,
          width: 170,
        },
      ],
      dataSource: [],
      dataSourceJS: [
        {
          id: 1,
          name: 'Elvera Sleite',
          email: 'hboshers50@narod.ru',
          type: 'product manager',
          age: 30,
          paid: true,
        },
        {
          id: 2,
          name: 'Richardo Durrett',
          email: 'mhamsleyt@ask.com',
          type: 'UX/UI',
          age: 18,
          paid: false,
        },
        {
          id: 3,
          name: 'Ellwood Halsted',
          email: 'amccardle5h@godaddy.com',
          type: 'designer',
          age: 14,
          paid: true,
        },
        {
          id: 4,
          name: 'Tyson Anersen',
          email: 'hstrettell3c@list-manage.com',
          type: 'UX/UI',
          age: 32,
          paid: true,
        },
        {
          id: 5,
          name: 'Tobey Mordy',
          email: 'gfraschetti54@independent.co.uk',
          type: 'designer',
          age: 22,
          paid: true,
        },
        {
          id: 6,
          name: 'Leena Stovine',
          email: 'prawlingson4w@phoca.cz',
          type: 'designer',
          age: 17,
          paid: false,
        },
        {
          id: 7,
          name: 'Erinn Olenchenko',
          email: 'cmeddows1q@aboutads.info',
          type: 'UX/UI',
          age: 17,
          paid: false,
        },
        {
          id: 8,
          name: 'Jilly Aldiss',
          email: 'radamik2b@hubpages.com',
          type: 'marketing',
          age: 22,
          paid: false,
        },
        {
          id: 9,
          name: 'Erinn Reasce',
          email: 'aduckeru@scribd.com',
          type: 'designer',
          age: 24,
          paid: false,
        },
        {
          id: 10,
          name: 'Sargent Guy',
          email: 'jmaccafferky57@archive.org',
          type: 'marketing',
          age: 19,
          paid: false,
        },
        {
          id: 11,
          name: 'Gay Craiker',
          email: 'ddurrett42@yahoo.com',
          type: ['UX/UI', 'designer'],
          age: 27,
          paid: false,
        },
        {
          id: 12,
          name: 'Piper Sorey',
          email: 'dscanterburyx@topsy.com',
          type: 'designer',
          age: 25,
          paid: true,
        },
        {
          id: 13,
          name: 'Renato Benjefield',
          email: 'dmayfield27@seattletimes.com',
          type: 'marketing',
          age: 27,
          paid: true,
        },
        {
          id: 14,
          name: 'Adelind Loache',
          email: 'vhessel2w@sciencedirect.com',
          type: ['designer', 'UX/UI'],
          age: 14,
          paid: true,
        },
        {
          id: 15,
          name: 'Pepi Corssen',
          email: 'bfifield2v@amazonaws.com',
          type: ['product manager', 'designer'],
          age: 27,
          paid: false,
        },
      ],
      dataSourceMode: 'dynamic',
      enablePagination: false,
      excludeHiddenColumns: true,
      sortOrder: 'default',
      displayName: 'dataGrid1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'DATA_GRID_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        loading: 'Boolean',
        primaryKey: 'String',
        sortKey: 'String',
        rowSelection: 'Boolean',
        enablePagination: 'Boolean',
        enableServerSidePagination: 'Boolean',
        totalRowCount: 'Number',
        pageSize: 'Number',
        page: 'Number',
        pageSizeOptions: 'Array',
        densitySetting: 'Boolean',
        columnSetting: 'Boolean',
        refreshSetting: 'Boolean',
        exportSetting: 'Boolean',
        exportAllSetting: 'Boolean',
        filterSetting: 'Boolean',
        quickFilterSetting: 'Boolean',
        excludeHiddenColumns: 'Boolean',
      },
      pageSize: 5,
      page: 0,
      selectedRowsPrimaryKeys: [],
      selectedRows: [],
    },
    container1: {
      $dynamicAttrPaths: [],
      backgroundColor: '#ffffffff',
      currentIndex: 0,
      currentKey: 'View 1',
      dynamicHeight: 'auto',
      padding: {
        mode: 'all',
        size: '24',
      },
      radius: '4px',
      resizeDirection: 'HORIZONTAL',
      shadow: 'small',
      viewList: [
        {
          id: '391bfe4b-70d0-4c27-b75f-1b117031e923',
          key: 'View 1',
          label: 'View 1',
        },
        {
          id: '6c97c982-877a-46f7-ad30-94d8b7979c15',
          key: 'View 2',
          label: 'View 2',
        },
        {
          id: 'c77e6a30-652e-425d-90b8-f7a36145f8e4',
          key: 'View 3',
          label: 'View 3',
        },
      ],
      displayName: 'container1',
      $parentNode: 'bodySection1-bodySectionContainer1',
      $type: 'WIDGET',
      $widgetType: 'CONTAINER_WIDGET',
      $childrenNode: ['canvas1', 'canvas2', 'canvas3'],
      $parentPageName: 'page1',
      $validationPaths: {
        viewList: [
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
          {
            key: 'String',
            label: 'String',
            disabled: 'Boolean',
            hidden: 'Boolean',
          },
        ],
        tooltipText: 'String',
      },
    },
    button1: {
      $dynamicAttrPaths: [],
      colorScheme: 'blue',
      events: [
        {
          eventType: 'click',
          id: 'events-36330e2e-e37d-48e9-b77c-09ec25ea768d',
          method: 'trigger',
          targetId: 'query1',
          type: 'datasource',
        },
        {
          actionType: 'datasource',
          eventType: 'click',
          id: 'events-02f78d57-925c-4791-b1a9-890aae2d5d90',
        },
      ],
      hidden: false,
      text: '{}',
      variant: 'fill',
      displayName: 'button1',
      $parentNode: 'canvas1',
      $type: 'WIDGET',
      $widgetType: 'BUTTON_WIDGET',
      $childrenNode: [],
      $parentPageName: 'page1',
      $validationPaths: {
        text: 'String',
        events: [
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
          {
            widgetSwitchTargetValue: 'Boolean',
            pageIndex: 'Number',
            sortKey: 'String',
            sortOrder: 'String',
            filters: 'Array',
            operator: 'String',
            disabled: 'Boolean',
            script: 'String',
            url: 'String',
            newTab: 'Boolean',
            key: 'String',
            index: 'Number',
            showNextViewLoopBack: 'Boolean',
            showNextVisibleViewLoopBack: 'Boolean',
            showPreviousViewLoopBack: 'Boolean',
            showPreviousVisibleViewLoopBack: 'Boolean',
            title: 'String',
            description: 'String',
            pagePath: 'String',
            viewPath: 'String',
            duration: 'Number',
            fileName: 'String',
            fileType: 'String',
            enabled: 'Boolean',
            widgetTargetValue: 'String',
          },
        ],
        loading: 'Boolean',
        disabled: 'Boolean',
        tooltipText: 'String',
        hidden: 'Boolean',
      },
    },
    builderInfo: {
      version: '4.8.3',
      language: 'English',
    },
    currentUserInfo: {
      userID: 'ILAfx4p1C7dZ',
      nickname: 'root',
      email: 'root',
      language: 'en-US',
      createdAt: '2024-10-17T04:43:25.519489Z',
      updatedAt: '2024-10-17T04:44:07.468633Z',
    },
    urlParams: {
      query: {},
      url: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
      appURL: 'http://localhost:3000/0/app/ILAfx4p1C7dZ',
    },
    localStorage: {},
    currentPageInfo: {
      pagePath: 'page1',
      $dynamicAttrPaths: ['pagePath', 'subPagePath'],
    },
    pageInfos: [
      {
        pagePath: '/page1',
        subPagePath: '/page1/sub-page1',
        pageName: 'page1',
        subPageName: 'sub-page1',
        isHomePage: true,
        subPageGroup: '',
      },
    ],
  },
};
